driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.8.0

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list: chef-sugar::default
