driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: fedora-19
  - name: ubuntu-1004
  - name: ubuntu-12.04
  - name: freebsd-9.2
    run_list:
    - recipe[freebsd::portsnap]

suites:
- name: default
  run_list:
  - recipe[git]
  - recipe[git_test::default]
  attributes: {}

- name: source
  excludes: ["ubuntu-12.04", "ubuntu-10.04"]
  run_list:
  - recipe[git::source]
  attributes: {}

- name: server
  run_list:
  - recipe[git::server]
  attributes: {}
