---
driver:
   name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.0.3
  data_path: test/fixtures

platforms:
- name: centos-6.5
  run_list:
  - recipe[yum]
- name: centos-7.0
  run_list:
  - recipe[yum]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: debian-7.6
  run_list:
  - recipe[apt]
- name: fedora-21
  run_list:
  - recipe[yum]
- name: freebsd-10.1
# Cannot pull from repo when not in EC2
#- name: amazon-2014.3
#  driver:
#    box: amazon-linux64-2014.03
#    box_url: http://images.geekandi.com/amazon-linux/vagrant-amazon-linux64-2014.03-public-virtualbox.box
# Unsupported by omnibus-chef installation script
#- name: arch
#  driver:
#    box: arch-2013.02.01
#    box_url: http://cloud.terry.im/vagrant/archlinux-x86_64.box
#  run_list:
#  - recipe[pacman]
#- name: redhat
- name: scientific-6.4
  driver:
    box: lyte-scientific-6-minimal
    box_url: http://lyte.id.au/vagrant/sl6-64-lyte.box
- name: opensuse-13.1
  driver:
    box: opscode-opensuse-13.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.1-x86_64_chef-provisionerless.box
  run_list:
  - recipe[zypper]

suites:
- name: default
  attributes:
    machine_fqdn: working.computers.biz
    machine_fqdn_as_hostname: true
  run_list:
  - recipe[fqdn]
  - recipe[apache2_test::setup]
  - recipe[apache2_test::default]
  - recipe[apache2_test::basic_web_app]
  - recipe[apache2_test::broken_conf]
  - recipe[apache2_test::modules]
  - recipe[apache2_test::mod_ssl]
  - recipe[apache2_test::mod_auth_basic]
  - recipe[apache2_test::mod_auth_digest]
# - recipe[apache2_test::mod_auth_openid]
# - recipe[apache2_test::mod_authnz_ldap]
  - recipe[apache2_test::mod_authz_groupfile]
  - recipe[apache2_test::mod_authz_listed_host]
  - recipe[apache2_test::mod_authz_unlisted_host]
  - recipe[apache2_test::mod_authz_user]
  - recipe[apache2_test::mod_cgi]
# not supported by apache 2.4 without source compile with non-maintainer patches
# - recipe[apache2_test::mod_fastcgi]
# - recipe[apache2_test::mod_dav_svn]
  - recipe[apache2_test::mod_expires]
  - recipe[apache2_test::mod_status_remote]
- name: prefork
  includes: [
    'centos-6.5',
    'ubuntu-14.04'
  ]
  attributes:
    machine_fqdn: working.computers.biz
    machine_fqdn_as_hostname: true
    apache:
      mpm: prefork
  run_list:
  - recipe[fqdn]
  - recipe[apache2_test::setup]
  - recipe[apache2_test::default]
  - recipe[apache2_test::broken_conf]
  - recipe[apache2_test::modules]
  - recipe[apache2_test::mod_cgi]
  - recipe[apache2_test::mod_fastcgi]
  - recipe[apache2_test::mod_perl]
  - recipe[apache2_test::mod_php5]
# - recipe[apache2_test::mod_proxy_ajp]
  - recipe[apache2_test::mod_python]
  - recipe[apache2_test::mod_ssl]
- name: worker
  includes: [
    'centos-7.0',
    'ubuntu-12.04'
  ]
  attributes:
    machine_fqdn: working.computers.biz
    machine_fqdn_as_hostname: true
    apache:
      mpm: worker
  run_list:
  - recipe[fqdn]
  - recipe[apache2_test::setup]
  - recipe[apache2_test::default]
  - recipe[apache2_test::basic_web_app]
  - recipe[apache2_test::broken_conf]
  - recipe[apache2_test::modules]
- name: event
  includes: [
    'ubuntu-14.04'
  ]
  attributes:
    machine_fqdn: working.computers.biz
    machine_fqdn_as_hostname: true
    apache:
      mpm: event
  run_list:
  - recipe[fqdn]
  - recipe[apache2_test::setup]
  - recipe[apache2_test::default]
  - recipe[apache2_test::basic_web_app]
  - recipe[apache2_test::broken_conf]
  - recipe[apache2_test::modules]
