---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  google_client_email: <%= ENV['GOOGLE_CLIENT_EMAIL'] %>
  google_key_location: <%= ENV['GOOGLE_KEY_LOCATION'] %>
  google_project: <%= ENV['GOOGLE_PROJECT'] %>
  joyent_username: <%= ENV['SDC_CLI_ACCOUNT'] %>
  joyent_keyfile: <%= ENV['SDC_CLI_IDENTITY'] %>
  joyent_keyname: <%= ENV['SDC_CLI_KEY_ID'] %>
  joyent_url: <%= ENV['SDC_CLI_URL'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.12.8

platforms:
- name: centos-5.8
  driver_plugin: digitalocean
  driver_config:
    image_id: 1601
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: centos-6.5
  driver_plugin: digitalocean
  driver_config:
    image_id: 3448641
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: amazon-2013.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-3be4bc52
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: amazon-2014.03
  driver_plugin: ec2
  driver_config:
    image_id: ami-6b726502
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: suse-11.3
  driver_plugin: ec2
  driver_config:
    image_id: ami-e8084981
    username: root
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: redhat-6.5
  driver_plugin: ec2
  driver_config:
    image_id: ami-8d756fe4
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  run_list:
  - recipe[selinux]
  attributes:
    selinux:
      state: disabled

- name: fedora-20
  driver_plugin: digitalocean
  driver_config:
    image_id: 3243145
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: debian-7.0
  driver_plugin: gce
  driver_config:
    image_name: debian-7-wheezy-v20131120
    zone: <%= ENV['GCE_ZONE'] %>
    area: <%= ENV['GCE_AREA'] %>
    network: <%= ENV['GCE_NETWORK'] %>
    username: <%= ENV['GCE_USERNAME'] %>
    public_key_path: <%= ENV['GCE_PUBLIC_KEY_PATH'] %>
    ssh_key: <%= ENV['GCE_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  driver_plugin: digitalocean
  driver_config:
    image_id: 3101045
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_plugin: digitalocean
  driver_config:
    image_id: 3240036
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: smartos-13.4.0
  driver_plugin: joyent
  driver_config:
    joyent_image_id: ff86eb8a-a069-11e3-ae0e-4f3c8983a91c
    joyent_flavor_id: g3-standard-4-smartos
    username: root
    ssh_key: <%= ENV['SDC_CLI_IDENTITY'] %>
  busser:
    ruby_bindir: '/opt/local/bin/'
  provisioner:
    name: chef_zero
    sudo: false
    chef_omnibus_url: https://raw.github.com/test-kitchen/kitchen-joyent/master/scripts/install-smartos.sh

- name: omnios-151006
  driver_plugin: ec2
  driver_config:
    image_id: ami-35eb835c
    flavor_id: m3.medium
    username: root
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  provisioner:
    name: chef_zero
  run_list:
  - recipe[ips-omniti]

suites:
  - name: default
    attributes:
      machine_fqdn: working.computers.biz
      machine_fqdn_as_hostname: true
    run_list:
      - recipe[fqdn]
      - recipe[apache2_test::setup]
      - recipe[apache2_test::default]
      - recipe[apache2_test::basic_web_app]
      - recipe[apache2_test::modules]
      - recipe[apache2_test::mod_auth_basic]
      - recipe[apache2_test::mod_auth_digest]
      - recipe[apache2_test::mod_auth_openid]
      - recipe[apache2_test::mod_authnz_ldap]
      - recipe[apache2_test::mod_authz_groupfile]
      - recipe[apache2_test::mod_authz_listed_host]
      - recipe[apache2_test::mod_authz_unlisted_host]
      - recipe[apache2_test::mod_authz_user]
      - recipe[apache2_test::mod_cgi]
      - recipe[apache2_test::mod_dav_svn]
      - recipe[apache2_test::mod_expires]
      - recipe[apache2_test::mod_perl]
      - recipe[apache2_test::mod_php5]
      - recipe[apache2_test::mod_proxy_ajp]
      - recipe[apache2_test::mod_python]
      - recipe[apache2_test::mod_ssl]
      - recipe[apache2_test::mod_status_remote]
    includes: [
      'centos-5.8',
      'redhat-6.5',
      'centos-6.5',
      'amazon-2014.03',
      'fedora-19',
      'debian-7.0',
      'ubuntu-12.04',
      'ubuntu-14.04',
      'smartos-13.4.0',
      'omnios-151006',
      'suse-11.3'
    ]
