AllCops:
  Excludes:
    - vendor/**
    - ruby/**

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Max: 300
MethodLength:
  Max: 11
HashSyntax:
  EnforcedStyle: hash_rockets
IfUnlessModifier:
  Enabled: false
TrivialAccessors:
  ExactNameMatch: true
