---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[apqc_php::default]
  - name: drush
    run_list:
      - recipe[apqc_php::drush]
    attributes:
  - name: cli
    run_list:
      - recipe[apqc_php::sapi_cli]
    attributes:
  - name: mod_php
    run_list:
      - recipe[apqc_php::sapi_mod_php]
    attributes:
  - name: fpm
    run_list:
      - recipe[apqc_php::sapi_fpm]
    attributes:
